# Generated by Django 5.2.16 on 2026-07-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0002_seed_approved_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_title', models.TextField()),
                ('raw_price_text', models.TextField()),
                ('raw_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('url', models.TextField()),
                ('seller', models.TextField()),
                ('fetched_at', models.DateTimeField()),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_listings', to='sources.source')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source', 'external_id', 'fetched_at'), name='rawlisting_source_external_id_fetched_at_unique'), models.CheckConstraint(condition=models.Q(('raw_price__gte', 0)), name='rawlisting_raw_price_non_negative')],
            },
        ),
    ]
