# Generated by Django 5.2.16 on 2026-08-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rawlisting_immutability_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlisting',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawlisting',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
