# Generated by Django 5.2.17 on 2026-08-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_rawlisting_occurred_at_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('given_listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='swap_given', to='ingestion.rawlisting')),
                ('received_listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='swap_received', to='ingestion.rawlisting')),
            ],
        ),
    ]
