# Generated by Django 5.2.16 on 2026-07-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like new'), ('used', 'Used'), ('for_parts', 'For parts')], max_length=20)),
                ('day', models.DateField()),
                ('median', models.DecimalField(decimal_places=2, max_digits=12)),
                ('p25', models.DecimalField(decimal_places=2, max_digits=12)),
                ('p75', models.DecimalField(decimal_places=2, max_digits=12)),
                ('n_listings', models.PositiveIntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_points', to='catalogue.sku')),
            ],
        ),
        migrations.CreateModel(
            name='DealFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('reason', models.TextField()),
                ('flagged_at', models.DateTimeField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_flags', to='listings.listing')),
                ('baseline_pricepoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_flags', to='pricing.pricepoint')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pricepoint',
            constraint=models.UniqueConstraint(fields=('sku', 'condition', 'day'), name='pricepoint_sku_condition_day_unique'),
        ),
        migrations.AddConstraint(
            model_name='pricepoint',
            constraint=models.CheckConstraint(condition=models.Q(('p25__lte', models.F('median')), ('median__lte', models.F('p75'))), name='pricepoint_p25_median_p75_ordered'),
        ),
        migrations.AddConstraint(
            model_name='pricepoint',
            constraint=models.CheckConstraint(condition=models.Q(('n_listings__gte', 0)), name='pricepoint_n_listings_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='dealflag',
            constraint=models.UniqueConstraint(fields=('listing', 'baseline_pricepoint'), name='dealflag_listing_baseline_unique'),
        ),
    ]
