# Generated by Django 5.2.16 on 2026-07-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('ingestion', '0002_rawlisting_immutability_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like new'), ('used', 'Used'), ('for_parts', 'For parts')], max_length=20)),
                ('location', models.TextField()),
                ('resolution_confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('resolution_method', models.CharField(choices=[('exact_alias', 'Exact alias'), ('fuzzy_match', 'Fuzzy match'), ('human_confirmed', 'Human confirmed')], max_length=20)),
                ('resolved_at', models.DateTimeField()),
                ('raw_listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='listing', to='ingestion.rawlisting')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='catalogue.sku')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='listing_price_non_negative'), models.CheckConstraint(condition=models.Q(('resolution_confidence__gte', 0), ('resolution_confidence__lte', 1)), name='listing_resolution_confidence_in_unit_interval'), models.CheckConstraint(condition=models.Q(('condition__in', ['new', 'like_new', 'used', 'for_parts'])), name='listing_condition_in_vocabulary'), models.CheckConstraint(condition=models.Q(('resolution_method__in', ['exact_alias', 'fuzzy_match', 'human_confirmed'])), name='listing_resolution_method_in_vocabulary')],
            },
        ),
    ]
