# Generated by Django 5.2.16 on 2026-08-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('ingestion', '0003_rawlisting_occurred_at_payload'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='observed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_kind',
            field=models.CharField(blank=True, choices=[('asking', 'Asking'), ('realised', 'Realised')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='trade_side',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], default=None, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price_kind__in', ['asking', 'realised'])), name='listing_price_kind_in_vocabulary'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('trade_side__in', ['buy', 'sell'])), name='listing_trade_side_in_vocabulary'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('trade_side__isnull', True), ('price_kind', 'realised'), _connector='OR'), name='listing_trade_side_requires_realised_price_kind'),
        ),
    ]
