# Generated by Django 5.2.17 on 2026-08-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_observed_at_price_kind_trade_side'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='listing_resolution_method_in_vocabulary',
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like new'), ('used', 'Used'), ('for_parts', 'For parts')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='resolution_method',
            field=models.CharField(choices=[('exact_alias', 'Exact alias'), ('fuzzy_match', 'Fuzzy match'), ('human_confirmed', 'Human confirmed'), ('unresolved', 'Unresolved')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_method__in', ['exact_alias', 'fuzzy_match', 'human_confirmed', 'unresolved'])), name='listing_resolution_method_in_vocabulary'),
        ),
    ]
