# Generated by Django 5.2.17 on 2026-08-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_listing_resolution_method_in_vocabulary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='reviewed_unresolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
