# Generated by Django 5.2.16 on 2026-07-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('variant', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(choices=[('gpu', 'GPU'), ('cpu', 'CPU'), ('ram', 'RAM'), ('mobo', 'Motherboard'), ('monitor', 'Monitor'), ('peripheral', 'Peripheral')], max_length=20)),
                ('launch_msrp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('launch_date', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('brand', 'model', 'variant'), name='sku_brand_model_variant_unique'), models.CheckConstraint(condition=models.Q(('launch_msrp__gte', 0)), name='sku_launch_msrp_non_negative'), models.CheckConstraint(condition=models.Q(('category__in', ['gpu', 'cpu', 'ram', 'mobo', 'monitor', 'peripheral'])), name='sku_category_in_vocabulary')],
            },
        ),
        migrations.CreateModel(
            name='SkuAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.TextField()),
                ('normalised_text', models.TextField(unique=True)),
                ('source_of_truth', models.CharField(choices=[('human_confirmed', 'Human confirmed'), ('seed', 'Seed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalogue.sku')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('source_of_truth__in', ['human_confirmed', 'seed'])), name='skualias_source_of_truth_in_vocabulary')],
            },
        ),
    ]
