# Generated by Django 5.2.16 on 2026-07-30 14:31

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acted', models.BooleanField()),
                ('skip_reason', models.TextField(blank=True, null=True)),
                ('bought_at', models.DateTimeField(blank=True, null=True)),
                ('bought_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('days_held', models.PositiveIntegerField(blank=True, null=True)),
                ('realised_margin', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('sold_price'), '-', models.F('bought_price')), null=True, output_field=models.DecimalField(decimal_places=2, max_digits=12))),
            ],
        ),
    ]
