# Generated by Django 5.2.16 on 2026-07-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outcomes', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='deal_flag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='pricing.dealflag'),
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.CheckConstraint(condition=models.Q(('acted', True), models.Q(('skip_reason__isnull', False), models.Q(('skip_reason', ''), _negated=True)), _connector='OR'), name='outcome_skip_reason_required_when_not_acted'),
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.CheckConstraint(condition=models.Q(('days_held__gte', 0)), name='outcome_days_held_non_negative'),
        ),
    ]
