# Generated by Django 5.2.16 on 2026-07-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.TextField(blank=True, default='')),
                ('terms_notes', models.TextField()),
                ('rate_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('last_successful_fetch', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rate_limit__gt', 0)), name='source_rate_limit_positive'), models.CheckConstraint(condition=models.Q(('terms_notes', ''), _negated=True), name='source_terms_notes_not_blank')],
            },
        ),
    ]
